# Specify the template type. Valid values are as follows.
# - For Terraform: TF
# - For AWS CloudFormation: CFT
# - For Kubernetes: K8S
template_type: CFT				
# cft_parameters:
#  	variable_values:
#  	   - name: KeyName
#  		 value: 10
#  	   - name: AMI
#  		 value: ami-45785
